/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp2;

import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.lang.reflect.Array;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author raisy
 */
public class AddLaptop extends javax.swing.JFrame {

    /**
     * Creates new form Login1
     */
    private Home home;
    private dbConnection db;
    private boolean isUpdate;
    private int id;
    private String name;
    private File f = null;
    private String paths = null;
    private String newFilePath = null;
    private Path originalPath;
    private Path newPath;
    private int tempIdComponent = 0;
    public AddLaptop(Home home, boolean isUpdate, int id) {
        initComponents();
        
        db = new dbConnection();
        this.home = home;
        this.isUpdate = isUpdate;
        this.id = id;
        getDataComponent();
        
//      Check first, now update or insert
        if (this.isUpdate == false) {
            LabelPath.setVisible(false);
            imageView.setVisible(false);
            
//          If now is update, set text of button, clear button set to invis and set the color to yellow in the add button
        } else {
            LabelPath.setVisible(true);
            imageView.setVisible(true);
            AddDataButton.setText("Update");
            clearButton1.setVisible(false);
            AddDataButton.setBackground(new Color(204, 204, 0));
        }
    }
    
//  Reset Field
    public void resetForm() {
        // Set All Value Form to Empty
        merkLaptopField.setText("");
        modelLaptopField.setText("");
        jenisLaptopField.setText("");
        componentDrop.setSelectedItem(null);
    }
    
//  Call the procedure from home, for the reset panel
    public void notifydataupdate() {
        home.ondataupdated();
    }
    
//  Create the procedure for the set of text/item, for the update
    public void setUpdate(String merkLaptop, String modelLaptop, String jenisLaptop, String component, String path) {
        tempIdComponent = Integer.valueOf(component);
        componentDrop.addItem(component);
        
        merkLaptopField.setText(merkLaptop);
        modelLaptopField.setText(modelLaptop);
        jenisLaptopField.setText(jenisLaptop);
        componentDrop.setSelectedItem(component);
        LabelPath.setText(path);
        ImageIcon il = new ImageIcon(path);
        Image img = il.getImage().getScaledInstance(100, 130, Image.SCALE_SMOOTH);
        imageView.setIcon(new ImageIcon(img));
        imageView.setText(path);
        AddLabel.setText("Update Laptop");
    }

//  get the id from table layar, for input layar drop
    public void getDataComponent() {
        int idNotUsed = 0;
        ResultSet dbComponent = db.selectQuery("select * from component WHERE stats_used = '"+idNotUsed+"'");
        try {
            while (dbComponent.next()) {
                componentDrop.addItem(dbComponent.getString("id_component"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(AddComponent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        AddLabel = new javax.swing.JLabel();
        merkLaptopLabel = new javax.swing.JLabel();
        modelLaptopLabel = new javax.swing.JLabel();
        AddDataButton = new javax.swing.JButton();
        jenisLaptopLabel = new javax.swing.JLabel();
        clearButton1 = new javax.swing.JButton();
        imageLabel = new javax.swing.JLabel();
        componentDrop = new javax.swing.JComboBox<>();
        componentLabel = new javax.swing.JLabel();
        merkLaptopField = new javax.swing.JTextField();
        modelLaptopField = new javax.swing.JTextField();
        jenisLaptopField = new javax.swing.JTextField();
        browseImageButton = new javax.swing.JButton();
        LabelPath = new javax.swing.JLabel();
        imageView = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageBg/laptop_logo.png"))); // NOI18N
        jLabel1.setAlignmentX(0.5F);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 14, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Laptop Media");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 14, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageBg/back_icon.png"))); // NOI18N
        jButton1.setText(" Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 50));

        AddLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AddLabel.setForeground(new java.awt.Color(255, 255, 255));
        AddLabel.setText("Form Add Laptop");
        getContentPane().add(AddLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        merkLaptopLabel.setForeground(new java.awt.Color(255, 255, 255));
        merkLaptopLabel.setText("Merk Laptop       :");
        getContentPane().add(merkLaptopLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        modelLaptopLabel.setForeground(new java.awt.Color(255, 255, 255));
        modelLaptopLabel.setText("Model Laptop     :");
        getContentPane().add(modelLaptopLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        AddDataButton.setBackground(new java.awt.Color(51, 153, 0));
        AddDataButton.setForeground(new java.awt.Color(0, 0, 0));
        AddDataButton.setText("Add Data");
        AddDataButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddDataButtonMouseClicked(evt);
            }
        });
        AddDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDataButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AddDataButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, -1, -1));

        jenisLaptopLabel.setForeground(new java.awt.Color(255, 255, 255));
        jenisLaptopLabel.setText("Jenis Laptop       :");
        getContentPane().add(jenisLaptopLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        clearButton1.setBackground(new java.awt.Color(0, 153, 153));
        clearButton1.setForeground(new java.awt.Color(0, 0, 0));
        clearButton1.setText("Clear");
        clearButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearButton1MouseClicked(evt);
            }
        });
        clearButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(clearButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, -1, -1));

        imageLabel.setForeground(new java.awt.Color(255, 255, 255));
        imageLabel.setText("Image                :");
        getContentPane().add(imageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        getContentPane().add(componentDrop, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 220, -1));

        componentLabel.setForeground(new java.awt.Color(255, 255, 255));
        componentLabel.setText("Component       :");
        getContentPane().add(componentLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));
        getContentPane().add(merkLaptopField, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 120, 210, -1));
        getContentPane().add(modelLaptopField, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 160, 210, -1));
        getContentPane().add(jenisLaptopField, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 200, 210, -1));

        browseImageButton.setText("Browse...");
        browseImageButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                browseImageButtonMouseClicked(evt);
            }
        });
        getContentPane().add(browseImageButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 210, -1));

        LabelPath.setForeground(new java.awt.Color(255, 255, 255));
        LabelPath.setText("jLabel5");
        getContentPane().add(LabelPath, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 320, 210, -1));

        imageView.setText("jLabel5");
        getContentPane().add(imageView, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 100, 130));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageBg/bg_addLaptop.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 360, 460));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AddDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDataButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddDataButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void clearButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearButton1ActionPerformed

    private void clearButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearButton1MouseClicked
        // TODO add your handling code here:
        resetForm();
    }//GEN-LAST:event_clearButton1MouseClicked

//  Insert/Update statement
    private void AddDataButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddDataButtonMouseClicked
        // TODO add your handling code here:
        if (this.isUpdate == false) { //if now is insert
            String merkLaptop = merkLaptopField.getText();
            String modelLaptop = modelLaptopField.getText();
            String jenisLaptop = jenisLaptopField.getText();
            String component = componentDrop.getSelectedItem().toString();
            int idComp = Integer.valueOf(component), statsUsed = 1;
            String Image = "";
            if (newFilePath != null) {
                newFilePath = newFilePath.replace('/', File.separatorChar); 
            }
            int yes = JOptionPane.showConfirmDialog(null, "Anda yakin menginput data terkait ?", "Confirmation", JOptionPane.YES_NO_OPTION);
            if (JOptionPane.YES_OPTION == yes) {
                if (merkLaptop.isEmpty() || modelLaptop.isEmpty() || jenisLaptop.isEmpty() || component.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Please fill in the data completely!");
                } else {
                    String sql = "insert into laptop (id_laptop, merk_laptop, model_laptop, jenis_laptop, id_component, image_laptop) values (NULL, '"+merkLaptop+"', '"+modelLaptop+"', '"+jenisLaptop+"', '"+idComp+"', '"+newFilePath+"')";
                    String updateLayar = "UPDATE component SET stats_used='" + statsUsed + "' WHERE id_component=" + idComp;
                    db.updateQuery(updateLayar);
                    db.updateQuery(sql);
                    try {
                        Files.copy(originalPath, newPath, StandardCopyOption.REPLACE_EXISTING);
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                    JOptionPane.showMessageDialog(null, "Data has been successfully entered!");
                    dispose();
                    notifydataupdate();
                    home.selectedFilterLaptop();
                }
            }
        } else if (this.isUpdate == true) { //If now is update
            String merkLaptop = merkLaptopField.getText();
            String modelLaptop = modelLaptopField.getText();
            String jenisLaptop = jenisLaptopField.getText();
            String Id_Component = componentDrop.getSelectedItem().toString();
            String path = LabelPath.getText();
            int idComponent = Integer.parseInt(Id_Component);
            boolean idcomponentFlag = false, editImg = false;
            if (tempIdComponent != idComponent) { //Check if user change the idComponent
                idcomponentFlag = true;
            }
            if (newFilePath == null) { //Check if user change the image
                newFilePath = path;
                newFilePath = newFilePath.replace('/', File.separatorChar);
            } else {
                editImg = true;
                newFilePath = newFilePath.replace('/', File.separatorChar);
            }
            
            int statsUsed = 1, stats = 0, affectedRow = 0;

            int yes = JOptionPane.showConfirmDialog(null, "Anda yakin mengedit data terkait ?", "Confirmation", JOptionPane.YES_NO_OPTION);
            if (JOptionPane.YES_OPTION == yes) {
                if (merkLaptop.isEmpty() || modelLaptop.isEmpty() || jenisLaptop.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Please fill in the data completely!");
                } else {
                    String sql = "";
                    if (editImg == true ){
                        sql = "UPDATE laptop SET merk_laptop='" + merkLaptop + "', model_laptop='" + modelLaptop + "', jenis_laptop='" + jenisLaptop + "', id_component= '"+idComponent+"', image_laptop= '"+newFilePath+"' WHERE id_laptop=" + this.id;
                        try {
                            Files.copy(originalPath, newPath, StandardCopyOption.REPLACE_EXISTING);
                        } catch (IOException e) {
                            e.printStackTrace();
                        }
                    } else {
                        sql = "UPDATE laptop SET merk_laptop='" + merkLaptop + "', model_laptop='" + modelLaptop + "', jenis_laptop='" + jenisLaptop + "', id_component= '"+idComponent+"' WHERE id_laptop=" + this.id;
                    }
                    if (idcomponentFlag == true) {
                        String updateComponent = "UPDATE component SET stats_used='" + statsUsed + "' WHERE id_component=" + idComponent;
                        String anotherComponent = "UPDATE component SET stats_used='" + stats + "' WHERE id_component=" + tempIdComponent;
                        db.updateQuery(updateComponent);
                        db.updateQuery(anotherComponent);
                        
                        affectedRow = db.updateQuery(sql);
                        if (affectedRow > 0) {
                            JOptionPane.showMessageDialog(null, "Data has been successfully edited!");
                            dispose();
                            notifydataupdate();
                            home.selectedFilterLaptop();
                        } else {
                            JOptionPane.showMessageDialog(null, "Data Unsuccessfully Updated");
                            dispose();
                        }
                    } else {
                        affectedRow = db.updateQuery(sql);
                        if (affectedRow > 0) {
                            JOptionPane.showMessageDialog(null, "Data has been successfully edited!");
                            dispose();
                            notifydataupdate();
                            home.selectedFilterLaptop();
                        } else {
                            JOptionPane.showMessageDialog(null, "Data Unsuccessfully Updated");
                            dispose();
                        }
                    }
                }
            }
        }
            
        
    }//GEN-LAST:event_AddDataButtonMouseClicked

//  Browse the image
    private void browseImageButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_browseImageButtonMouseClicked
        // TODO add your handling code here:
        
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter fnwf = new FileNameExtensionFilter("PNG JPG AND JPEG", "png", "jpeg", "jpg");
        fileChooser.addChoosableFileFilter(fnwf);
        int load = fileChooser.showOpenDialog(null);
        
        if (load == fileChooser.APPROVE_OPTION) {
            f = fileChooser.getSelectedFile();
            paths = f.getAbsolutePath();
            
            File directory = new File("src//ImgUpload//"); // replace 
            if (!directory.exists()) {
                directory.mkdirs();
            }
            
//          Explode base and ext from original name file img
            String originalBase = f.getName().split("\\.")[0];
            String originalExt = f.getName().split("\\.")[1];
//            ===================================================
            
//          Process of a random generator name file from img file
            String SALTCHARS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890";
            StringBuilder salt = new StringBuilder();
            Random rnd = new Random();
            while (salt.length() < 7) { // length of the random string.
                int index = (int) (rnd.nextFloat() * SALTCHARS.length());
                salt.append(SALTCHARS.charAt(index));
            }
            String newBaseName = salt.toString().toLowerCase();
//          =======================================

            originalPath = Paths.get(paths);
            newPath = Paths.get(directory.getPath() + File.separator + newBaseName + "." + originalExt);

            newFilePath = "src//ImgUpload//" + newBaseName + "." + originalExt;
        }
    }//GEN-LAST:event_browseImageButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddLaptop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddLaptop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddLaptop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddLaptop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AddLayar().setVisible(true);
//            }
//        });
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AddLayar().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddDataButton;
    private javax.swing.JLabel AddLabel;
    private javax.swing.JLabel LabelPath;
    private javax.swing.JButton browseImageButton;
    private javax.swing.JButton clearButton1;
    private javax.swing.JComboBox<String> componentDrop;
    private javax.swing.JLabel componentLabel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel imageView;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jenisLaptopField;
    private javax.swing.JLabel jenisLaptopLabel;
    private javax.swing.JTextField merkLaptopField;
    private javax.swing.JLabel merkLaptopLabel;
    private javax.swing.JTextField modelLaptopField;
    private javax.swing.JLabel modelLaptopLabel;
    // End of variables declaration//GEN-END:variables
}
