/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tp2;

import java.awt.Image;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author raisy
 */
public class CardLaptop extends javax.swing.JPanel {

    /**
     * Creates new form CardLayar
     */
    private dbConnection db;
    private Home home;
    private int id;
    private int idComponent;
    private String pathImage;
    public CardLaptop(dbConnection db, Home home, int id, int dataLabel, String merkLaptop, String modelLaptop, String jenisLaptop, int idComponent, String path, String cpu, String vga, String ram, String hddssd, int idLayar, String ukuranLayar, String jenisLayar, String jenisPanel, String resolusiLayar, String keyboard, String camera) {
        initComponents();
        ImageIcon il = new ImageIcon(path);
        Image img = il.getImage().getScaledInstance(150, 342, Image.SCALE_SMOOTH);
        imageLabel.setIcon(new ImageIcon(img));
        imageLabel.setText(path);   
        merkLaptopLabel.setText(merkLaptop);
        modelLaptopLabel.setText(modelLaptop);
        jenisLaptopLabel.setText(jenisLaptop);
        
//        Component
        processorLabel.setText(cpu);
        ramLabel.setText(ram);
        hddssdLabel.setText(hddssd);
        vgaLabel.setText(vga);
        keyboardLabel.setText(keyboard);
        cameraLabel.setText(camera);
        
//        Layar
        ukuranLayarLabel.setText(ukuranLayar);
        jenisLayarLabel.setText(jenisLayar);
        jenisPanelLabel.setText(jenisPanel);
        resolusiLayarLabel.setText(resolusiLayar);
        
        this.home = home;
        this.id = id;
        this.idComponent = idComponent;
        this.db = db;
        this.pathImage = path;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageLabel = new javax.swing.JLabel();
        merkLaptop = new javax.swing.JLabel();
        modelLaptop = new javax.swing.JLabel();
        processor = new javax.swing.JLabel();
        resolusiLayar = new javax.swing.JLabel();
        merkLaptopLabel = new javax.swing.JLabel();
        modelLaptopLabel = new javax.swing.JLabel();
        ramLabel = new javax.swing.JLabel();
        hddssdLabel = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        resolusiLayar1 = new javax.swing.JLabel();
        processorLabel = new javax.swing.JLabel();
        resolusiLayar2 = new javax.swing.JLabel();
        vgaLabel = new javax.swing.JLabel();
        ukuranLayarLabel = new javax.swing.JLabel();
        resolusiLayar3 = new javax.swing.JLabel();
        processor1 = new javax.swing.JLabel();
        processor2 = new javax.swing.JLabel();
        resolusiLayar4 = new javax.swing.JLabel();
        keyboardLabel = new javax.swing.JLabel();
        resolusiLayar5 = new javax.swing.JLabel();
        cameraLabel = new javax.swing.JLabel();
        resolusiLayar6 = new javax.swing.JLabel();
        jenisLayarLabel = new javax.swing.JLabel();
        resolusiLayar7 = new javax.swing.JLabel();
        jenisPanelLabel = new javax.swing.JLabel();
        resolusiLayar8 = new javax.swing.JLabel();
        resolusiLayarLabel = new javax.swing.JLabel();
        merkLaptop1 = new javax.swing.JLabel();
        jenisLaptopLabel = new javax.swing.JLabel();

        merkLaptop.setText("Merk Laptop   :");

        modelLaptop.setText("Model Laptop      :");

        processor.setText("Processor");

        resolusiLayar.setText("RAM");

        merkLaptopLabel.setText("jLabel1");

        modelLaptopLabel.setText("jLabel1");

        ramLabel.setText("jLabel1");

        hddssdLabel.setText("jLabel1");

        deleteButton.setBackground(new java.awt.Color(153, 0, 0));
        deleteButton.setForeground(new java.awt.Color(0, 0, 0));
        deleteButton.setText("Delete");
        deleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteButtonMouseClicked(evt);
            }
        });
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        updateButton.setBackground(new java.awt.Color(204, 204, 0));
        updateButton.setForeground(new java.awt.Color(0, 0, 0));
        updateButton.setText("Update");
        updateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateButtonMouseClicked(evt);
            }
        });
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        resolusiLayar1.setText("HDD/SSD");

        processorLabel.setText("jLabel1");

        resolusiLayar2.setText("Graphics Card");

        vgaLabel.setText("jLabel1");

        ukuranLayarLabel.setText("jLabel1");

        resolusiLayar3.setText("Ukuran Layar");

        processor1.setText("Component of Laptop");

        processor2.setText("Detail Layar");

        resolusiLayar4.setText("Keyboard");

        keyboardLabel.setText("jLabel1");

        resolusiLayar5.setText("Camera");

        cameraLabel.setText("jLabel1");

        resolusiLayar6.setText("Jenis Layar");

        jenisLayarLabel.setText("jLabel1");

        resolusiLayar7.setText("Jenis Panel");

        jenisPanelLabel.setText("jLabel1");

        resolusiLayar8.setText("Resolusi Layar");

        resolusiLayarLabel.setText("jLabel1");

        merkLaptop1.setText("Jenis Laptop   :");

        jenisLaptopLabel.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(updateButton)
                        .addGap(18, 18, 18)
                        .addComponent(deleteButton)
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(merkLaptop)
                                    .addComponent(merkLaptop1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jenisLaptopLabel)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(merkLaptopLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                                        .addComponent(modelLaptop)
                                        .addGap(18, 18, 18)
                                        .addComponent(modelLaptopLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(resolusiLayar)
                                    .addComponent(processor)
                                    .addComponent(resolusiLayar1)
                                    .addComponent(resolusiLayar2)
                                    .addComponent(processor1)
                                    .addComponent(resolusiLayar4)
                                    .addComponent(resolusiLayar5))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hddssdLabel)
                                    .addComponent(ramLabel)
                                    .addComponent(processorLabel)
                                    .addComponent(vgaLabel)
                                    .addComponent(keyboardLabel)
                                    .addComponent(cameraLabel))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(processor2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(resolusiLayar3)
                                            .addComponent(resolusiLayar6)
                                            .addComponent(resolusiLayar7))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jenisPanelLabel)
                                            .addComponent(jenisLayarLabel)
                                            .addComponent(ukuranLayarLabel)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(resolusiLayar8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(resolusiLayarLabel)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(merkLaptop)
                    .addComponent(merkLaptopLabel)
                    .addComponent(modelLaptop)
                    .addComponent(modelLaptopLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(merkLaptop1)
                    .addComponent(jenisLaptopLabel))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(processor1)
                    .addComponent(processor2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(processor)
                    .addComponent(processorLabel)
                    .addComponent(ukuranLayarLabel)
                    .addComponent(resolusiLayar3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resolusiLayar)
                    .addComponent(ramLabel)
                    .addComponent(resolusiLayar6)
                    .addComponent(jenisLayarLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resolusiLayar1)
                    .addComponent(hddssdLabel)
                    .addComponent(resolusiLayar7)
                    .addComponent(jenisPanelLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resolusiLayar2)
                    .addComponent(vgaLabel)
                    .addComponent(resolusiLayar8)
                    .addComponent(resolusiLayarLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resolusiLayar4)
                    .addComponent(keyboardLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resolusiLayar5)
                    .addComponent(cameraLabel))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton)
                    .addComponent(updateButton))
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
//Update Button
    private void updateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateButtonMouseClicked
        // TODO add your handling code here:
        
        String merkLaptop = merkLaptopLabel.getText();
        String modelLaptop = modelLaptopLabel.getText();
        String jenisLaptop = jenisLaptopLabel.getText();
        String image = this.pathImage;
        
        int idComponent = this.idComponent;
        String component = String.valueOf(idComponent);
        
        boolean flag = true;
        AddLaptop updateSet = new AddLaptop(home, flag, this.id);
        updateSet.show();
        updateSet.setUpdate(merkLaptop, modelLaptop, jenisLaptop, component, image);
    }//GEN-LAST:event_updateButtonMouseClicked

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateButtonActionPerformed
//  Delete Button
    private void deleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseClicked
        // TODO add your handling code here:
        String sql = "DELETE FROM laptop WHERE id_laptop=" + this.id;
        int used = 1, statsNotUsed = 0;
        
        String updateComponent = "UPDATE component SET stats_used='" + statsNotUsed + "' WHERE id_component=" + this.idComponent;
        int yes = JOptionPane.showConfirmDialog(null, "Anda yakin menghapus data terkait ?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if (JOptionPane.YES_OPTION == yes) {
            int affectedRow = db.updateQuery(sql);
            if (affectedRow > 0) {
                // Update Card
                db.updateQuery(updateComponent);
                home.ondataupdated();

                // Show Information
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
            } else {
                JOptionPane.showMessageDialog(null, "Data gagal dihapus!");
            }
        }          
    }//GEN-LAST:event_deleteButtonMouseClicked

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cameraLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel hddssdLabel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jenisLaptopLabel;
    private javax.swing.JLabel jenisLayarLabel;
    private javax.swing.JLabel jenisPanelLabel;
    private javax.swing.JLabel keyboardLabel;
    private javax.swing.JLabel merkLaptop;
    private javax.swing.JLabel merkLaptop1;
    private javax.swing.JLabel merkLaptopLabel;
    private javax.swing.JLabel modelLaptop;
    private javax.swing.JLabel modelLaptopLabel;
    private javax.swing.JLabel processor;
    private javax.swing.JLabel processor1;
    private javax.swing.JLabel processor2;
    private javax.swing.JLabel processorLabel;
    private javax.swing.JLabel ramLabel;
    private javax.swing.JLabel resolusiLayar;
    private javax.swing.JLabel resolusiLayar1;
    private javax.swing.JLabel resolusiLayar2;
    private javax.swing.JLabel resolusiLayar3;
    private javax.swing.JLabel resolusiLayar4;
    private javax.swing.JLabel resolusiLayar5;
    private javax.swing.JLabel resolusiLayar6;
    private javax.swing.JLabel resolusiLayar7;
    private javax.swing.JLabel resolusiLayar8;
    private javax.swing.JLabel resolusiLayarLabel;
    private javax.swing.JLabel ukuranLayarLabel;
    private javax.swing.JButton updateButton;
    private javax.swing.JLabel vgaLabel;
    // End of variables declaration//GEN-END:variables
}
