/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tp2;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author raisy
 */
public class CardComponent extends javax.swing.JPanel {

    /**
     * Creates new form CardLayar
     */
    private dbConnection db;
    private Home home;
    private int id;
    private int idLayar;
    public CardComponent(dbConnection db, Home home, int id, int dataLabel, String cpu, String vga, String ram, String hddssd, int idLayar, String ukuranLayar, String jenisLayar, String jenisPanel, String resolusiLayar, String keyboard, String camera) {
        initComponents();
        
        this.home = home;
        this.id = id;
        this.db = db;
        this.idLayar = idLayar;
        
        DataLabel.setText("Data Ke - " + String.valueOf(dataLabel));
        cpuLabel.setText(cpu);
        ramLabel.setText(ram);
        vgaLabel.setText(vga);
        hddssdLabel.setText(hddssd);
        ukuranLayarLabel.setText(ukuranLayar);
        jenisLayarLabel.setText(jenisLayar);
        jenisPanelLabel.setText(jenisPanel);
        resolusiLayarLabel.setText(resolusiLayar);
        keyboardLabel.setText(keyboard);
        cameraLabel.setText(camera);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DataLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        listComponentLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cpuLabel = new javax.swing.JLabel();
        ramLabel = new javax.swing.JLabel();
        vgaLabel = new javax.swing.JLabel();
        hddssdLabel = new javax.swing.JLabel();
        ukuranLayarLabel = new javax.swing.JLabel();
        jenisLayarLabel = new javax.swing.JLabel();
        jenisPanelLabel = new javax.swing.JLabel();
        resolusiLayarLabel = new javax.swing.JLabel();
        cameraLabel = new javax.swing.JLabel();
        keyboardLabel = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();

        DataLabel.setText("     jLabel1");

        jLabel2.setText("CPU   :");

        jLabel3.setText("RAM  :");

        jLabel4.setText("VGA   :");

        jLabel5.setText("HDD/SSD  :");

        listComponentLabel.setText("Component Layar");

        jLabel7.setText("- Ukuran Layar    :");

        jLabel8.setText("Camera     :");

        jLabel9.setText("Keyboard  :");

        jLabel10.setText("- Jenis Layar        :");

        jLabel11.setText("- Jenis Panel        :");

        jLabel12.setText("- Resolusi Layar   :");

        cpuLabel.setText("jLabel1");

        ramLabel.setText("jLabel1");

        vgaLabel.setText("jLabel1");

        hddssdLabel.setText("jLabel1");

        ukuranLayarLabel.setText("jLabel1");

        jenisLayarLabel.setText("jLabel1");

        jenisPanelLabel.setText("jLabel1");

        resolusiLayarLabel.setText("jLabel1");

        cameraLabel.setText("jLabel1");

        keyboardLabel.setText("jLabel1");

        deleteButton.setBackground(new java.awt.Color(153, 0, 0));
        deleteButton.setForeground(new java.awt.Color(0, 0, 0));
        deleteButton.setText("Delete");
        deleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteButtonMouseClicked(evt);
            }
        });

        updateButton.setBackground(new java.awt.Color(204, 204, 0));
        updateButton.setForeground(new java.awt.Color(0, 0, 0));
        updateButton.setText("Update");
        updateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateButtonMouseClicked(evt);
            }
        });
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(jenisPanelLabel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(jenisLayarLabel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(18, 18, 18)
                                        .addComponent(resolusiLayarLabel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(ukuranLayarLabel))))
                            .addComponent(listComponentLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(keyboardLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                    .addComponent(cameraLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(updateButton)
                        .addGap(18, 18, 18)
                        .addComponent(deleteButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(hddssdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ramLabel)
                                    .addComponent(vgaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(cpuLabel)))
                        .addGap(0, 66, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DataLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpuLabel)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ramLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(vgaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(hddssdLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deleteButton)
                            .addComponent(updateButton))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(listComponentLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(ukuranLayarLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jenisLayarLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jenisPanelLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(resolusiLayarLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cameraLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(keyboardLabel))
                        .addGap(39, 39, 39))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateButtonActionPerformed

//  Delete Button
    private void deleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseClicked
        // TODO add your handling code here:
        int statsNotUsed = 0;
        String sql = "DELETE FROM component WHERE id_component=" + this.id;
        String updateLayar = "UPDATE layar SET stats_used='" + statsNotUsed + "' WHERE id_layar=" + this.idLayar;
        ResultSet find = db.selectQuery("select stats_used from component WHERE id_component=" + this.id);
        try {
            if (find.next()) {
                if (find.getInt("stats_used") == 0) {
                    int yes = JOptionPane.showConfirmDialog(null, "Anda yakin menghapus data terkait ?", "Confirmation", JOptionPane.YES_NO_OPTION);
                    if (JOptionPane.YES_OPTION == yes) {
                        int affectedRow = db.updateQuery(sql);
                        if (affectedRow > 0) {
                            // Update Card
                            db.updateQuery(updateLayar);
                            home.ondataupdated();

                            // Show Information
                            JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
                        } else {
                            JOptionPane.showMessageDialog(null, "Data gagal dihapus!");
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Data has been used in the other table!");
                    deleteButton.setText("Used");
                    deleteButton.setEnabled(false);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(CardComponent.class.getName()).log(Level.SEVERE, null, ex);
        }
                    
    }//GEN-LAST:event_deleteButtonMouseClicked

    private void updateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateButtonMouseClicked
//      Update Button
        String cpu = cpuLabel.getText();
        String ram = ramLabel.getText();
        String vga = vgaLabel.getText();
        String hddssd = hddssdLabel.getText();
        String ukuranLayar = ukuranLayarLabel.getText();
        String jenisLayar = jenisLayarLabel.getText();
        String jenisPanel = jenisPanelLabel.getText();
        String resolusiLayar = resolusiLayarLabel.getText();
        String keyboard = keyboardLabel.getText();
        String camera = cameraLabel.getText();
        int idLayar = this.idLayar;
        String layar = String.valueOf(idLayar);
        boolean flag = true;
        AddComponent updateSet = new AddComponent(home, flag, this.id);
        updateSet.show();
        updateSet.setUpdate(cpu, vga, ram, hddssd, layar, keyboard, camera);
    }//GEN-LAST:event_updateButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DataLabel;
    private javax.swing.JLabel cameraLabel;
    private javax.swing.JLabel cpuLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel hddssdLabel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jenisLayarLabel;
    private javax.swing.JLabel jenisPanelLabel;
    private javax.swing.JLabel keyboardLabel;
    private javax.swing.JLabel listComponentLabel;
    private javax.swing.JLabel ramLabel;
    private javax.swing.JLabel resolusiLayarLabel;
    private javax.swing.JLabel ukuranLayarLabel;
    private javax.swing.JButton updateButton;
    private javax.swing.JLabel vgaLabel;
    // End of variables declaration//GEN-END:variables
}
