/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tp2;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author raisy
 */
public class CardLayar extends javax.swing.JPanel {

    /**
     * Creates new form CardLayar
     */
    private dbConnection db;
    private Home home;
    private int id;
    public CardLayar(dbConnection db, Home home, int id, int dataLabel, String ukuranLayar, String jenisLayar, String jenisPanel, String resolusiLayar) {
        initComponents();
        DataLabel.setText("Data Ke - " + String.valueOf(dataLabel));
        showUkuranLayar.setText(ukuranLayar);
        showJenisLayar.setText(jenisLayar);
        showJenisPanel.setText(jenisPanel);
        showResolusiLayar.setText(resolusiLayar);
        this.home = home;
        this.id = id;
        this.db = db;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DataLabel = new javax.swing.JLabel();
        ukuranLayar = new javax.swing.JLabel();
        jenisLayar = new javax.swing.JLabel();
        jenisPanel = new javax.swing.JLabel();
        resolusiLayar = new javax.swing.JLabel();
        showUkuranLayar = new javax.swing.JLabel();
        showJenisLayar = new javax.swing.JLabel();
        showJenisPanel = new javax.swing.JLabel();
        showResolusiLayar = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();

        DataLabel.setText("     jLabel1");

        ukuranLayar.setText("Ukuran Layar   :");

        jenisLayar.setText("Jenis Layar       :");

        jenisPanel.setText("Jenis Panel       :");

        resolusiLayar.setText("Resolusi Layar  :");

        showUkuranLayar.setText("jLabel1");

        showJenisLayar.setText("jLabel1");

        showJenisPanel.setText("jLabel1");

        showResolusiLayar.setText("jLabel1");

        deleteButton.setBackground(new java.awt.Color(153, 0, 0));
        deleteButton.setForeground(new java.awt.Color(0, 0, 0));
        deleteButton.setText("Delete");
        deleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteButtonMouseClicked(evt);
            }
        });
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        updateButton.setBackground(new java.awt.Color(204, 204, 0));
        updateButton.setForeground(new java.awt.Color(0, 0, 0));
        updateButton.setText("Update");
        updateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateButtonMouseClicked(evt);
            }
        });
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ukuranLayar)
                            .addComponent(jenisLayar)
                            .addComponent(jenisPanel)
                            .addComponent(resolusiLayar))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(showResolusiLayar)
                            .addComponent(showJenisPanel)
                            .addComponent(showJenisLayar)
                            .addComponent(showUkuranLayar))
                        .addContainerGap(114, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(updateButton)
                        .addGap(18, 18, 18)
                        .addComponent(deleteButton)
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DataLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ukuranLayar)
                    .addComponent(showUkuranLayar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jenisLayar)
                    .addComponent(showJenisLayar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jenisPanel)
                    .addComponent(showJenisPanel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resolusiLayar)
                    .addComponent(showResolusiLayar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton)
                    .addComponent(updateButton))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents
//  Button Update
    private void updateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateButtonMouseClicked
        // TODO add your handling code here:
        String suk = showUkuranLayar.getText();
        String sjl = showJenisLayar.getText();
        String sjp = showJenisPanel.getText();
        String srl = showResolusiLayar.getText();
        boolean flag = true;
        AddLayar updateSet = new AddLayar(home, flag, this.id);
        updateSet.show();
        updateSet.setUpdate(suk, sjl, sjp, srl);
    }//GEN-LAST:event_updateButtonMouseClicked

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseClicked
        // TODO add your handling code here:
//      Button Delete
        String sql = "DELETE FROM layar WHERE id_layar=" + this.id;
        int used = 1;
        ResultSet find = db.selectQuery("select stats_used from layar WHERE id_layar=" + this.id);
        try {
            if (find.next()) {
                if (find.getInt("stats_used") == 0) {
                    int affectedRow = db.updateQuery(sql);
                    int yes = JOptionPane.showConfirmDialog(null, "Anda yakin menghapus data terkait ?", "Confirmation", JOptionPane.YES_NO_OPTION);
                    if (JOptionPane.YES_OPTION == yes) {
                        if (affectedRow > 0) {
                            // Update Card
                            home.ondataupdated();

                            // Show Information
                            JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
                        } else {
                            JOptionPane.showMessageDialog(null, "Data gagal dihapus!");
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Data has been used in the other table!");
                    deleteButton.setText("Used");
                    deleteButton.setEnabled(false);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(CardLayar.class.getName()).log(Level.SEVERE, null, ex);
        }
                    
    }//GEN-LAST:event_deleteButtonMouseClicked

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DataLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jenisLayar;
    private javax.swing.JLabel jenisPanel;
    private javax.swing.JLabel resolusiLayar;
    private javax.swing.JLabel showJenisLayar;
    private javax.swing.JLabel showJenisPanel;
    private javax.swing.JLabel showResolusiLayar;
    private javax.swing.JLabel showUkuranLayar;
    private javax.swing.JLabel ukuranLayar;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
