/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp2;

import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;
import javax.swing.JOptionPane;

/**
 *
 * @author raisy
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Login1
     */
    private dbConnection db;
    private dbConnection db2;
    private dbConnection db3;
    private String name;
    public Home(String name) {
        initComponents();
        
        db = new dbConnection();
        db2 = new dbConnection();
        db3 = new dbConnection();
        System.out.println(name);
        this.name = name;
        nameAccountLabel.setText("Halo, " + name);
        AddDropDown.setSelectedItem(null);
        FilterDropDown.setSelectedItem(null);
//        Penanda buat waktu kapan dia login
        Date NOW = new Date();
        timeLogin.setText(new SimpleDateFormat("HH:mm").format(NOW));
        
//        View Time
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date NOW = new Date();
                timeShow.setText(new SimpleDateFormat("HH:mm:ss aa").format(NOW));
            }
        });
        timer.start();
    }

    private Home() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
//    Reset/Cancel Button for clear the field
    public void resetForm() {
        AddDropDown.setSelectedItem(null);
        FilterDropDown.setSelectedItem(null);
        mainPanel.removeAll();
        mainPanel.revalidate();
        mainPanel.repaint();
    }
    
//    Clear the panel for view the refresh card
    public void ondataupdated() {
        AddDropDown.setSelectedItem(null);
        FilterDropDown.setSelectedItem(null);
        mainPanel.removeAll();
        mainPanel.revalidate();
        mainPanel.repaint();
    }
    
//    selectedData after user insert the selected data
    public void selectedFilterLayar() {
        FilterDropDown.setSelectedItem("Data Layar");
    }
    
    public void selectedFilterComponent() {
        FilterDropDown.setSelectedItem("Data Component");
    }
    
    public void selectedFilterLaptop() {
        FilterDropDown.setSelectedItem("Data Laptop");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AddDropDown = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        FilterDropDown = new javax.swing.JComboBox<>();
        ClearButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        timeLogin = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        timeShow = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageBg/laptop_logo.png"))); // NOI18N
        jLabel1.setAlignmentX(0.5F);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Laptop Media");

        nameAccountLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameAccountLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 51));
        jLabel9.setText("LogOut");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Select Add :");

        AddDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Add Data Laptop", "Add Data Component", "Add Data Layar" }));
        AddDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDropDownActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Filter Data :");

        FilterDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Data Laptop", "Data Component", "Data Layar" }));
        FilterDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilterDropDownActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(AddDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(FilterDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nameAccountLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(7, 7, 7))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(nameAccountLabel)
                        .addComponent(jLabel2)
                        .addComponent(AddDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(FilterDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        ClearButton.setBackground(new java.awt.Color(51, 204, 0));
        ClearButton.setForeground(new java.awt.Color(0, 0, 0));
        ClearButton.setText("Clear Selected");
        ClearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClearButtonMouseClicked(evt);
            }
        });
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 806, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 241, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(mainPanel);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Copyright RJ 2023");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Login On");

        timeLogin.setForeground(new java.awt.Color(255, 255, 255));
        timeLogin.setText("Time Login");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(35, 35, 35)
                .addComponent(timeLogin)
                .addGap(33, 33, 33))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(timeLogin))
                .addGap(14, 14, 14))
        );

        jLabel6.setText("Time");

        timeShow.setText("time");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ClearButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 570, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(41, 41, 41)
                        .addComponent(timeShow)
                        .addGap(58, 58, 58))))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(timeShow))
                    .addComponent(ClearButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void ClearButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearButtonMouseClicked
        // TODO add your handling code here:
        resetForm();
    }//GEN-LAST:event_ClearButtonMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
//        Logout Button
        dispose();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void AddDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDropDownActionPerformed
        // TODO add your handling code here:
        if (AddDropDown.getSelectedItem() != null) {
            String selectedDrop = AddDropDown.getSelectedItem().toString();
            boolean isUpdate = false;
            AddLayar formlayar = new AddLayar(this, isUpdate, 0);
            AddComponent formcomponent = new AddComponent(this, isUpdate, 0);
            AddLaptop formlaptop = new AddLaptop(this, isUpdate, 0);
            if (selectedDrop.equals("Add Data Layar")) {
                formlayar.show();
            } else if (selectedDrop.equals("Add Data Component")) {
                formcomponent.show();
            } else if (selectedDrop.equals("Add Data Laptop")) {
                formlaptop.show();
            }
        }
            
    }//GEN-LAST:event_AddDropDownActionPerformed

    private void FilterDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilterDropDownActionPerformed
        // TODO add your handling code here:
        if (FilterDropDown.getSelectedItem() != null) {
            String selectedFilter = FilterDropDown.getSelectedItem().toString();
            
//          Selected Data Layar
            if (selectedFilter.equals("Data Layar")) {
                mainPanel.removeAll();
                mainPanel.setLayout(new GridLayout(0, 1));
                int count = 1;
                ResultSet dbLayar = db.selectQuery("select * from layar");
                int id = 0;
                try {
                    while (dbLayar.next()) {
                        id = dbLayar.getInt("id_layar");
                        mainPanel.add(new CardLayar(db, this, id, count, dbLayar.getString("ukuran_layar"), dbLayar.getString("jenis_layar"), dbLayar.getString("jenis_panel"), dbLayar.getString("resolusi_layar")));
                        count++;
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(AddComponent.class.getName()).log(Level.SEVERE, null, ex);
                }
                mainPanel.revalidate();
                mainPanel.repaint();
                
//          Selected Data Component
            } else if (selectedFilter.equals("Data Component")) {
                mainPanel.removeAll();
                mainPanel.setLayout(new GridLayout(0, 1));
                int count = 1, id = 0, idLayar = 0;
                ResultSet dbComponent = db.selectQuery("select * from component");
                String ukuranLayar = "", jenisLayar = "", jenisPanel = "", resolusiLayar = "";
                
                try {
                    while (dbComponent.next()) {
                        id = dbComponent.getInt("id_component");
                        idLayar = dbComponent.getInt("id_layar");
                        ResultSet dbLayar = db2.selectQuery("select * from layar WHERE id_layar='"+idLayar+"'");
                        try {
                            if (dbLayar.next()) {
                                ukuranLayar = dbLayar.getString("ukuran_layar");
                                jenisLayar = dbLayar.getString("jenis_layar");
                                jenisPanel = dbLayar.getString("jenis_panel");
                                resolusiLayar = dbLayar.getString("resolusi_layar");
                            }
                        } catch (SQLException ex) {
                            Logger.getLogger(AddComponent.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        mainPanel.add(new CardComponent(db, this, id, count, dbComponent.getString("cpu"), dbComponent.getString("graphics_card"), dbComponent.getString("ram"), dbComponent.getString("hdd_ssd"), dbComponent.getInt("id_layar"), ukuranLayar, jenisLayar, jenisPanel, resolusiLayar, dbComponent.getString("keyboard"), dbComponent.getString("camera")));
                        count++;
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(AddComponent.class.getName()).log(Level.SEVERE, null, ex);
                }
                mainPanel.revalidate();
                mainPanel.repaint();
//          Selected Data Laptop
            } else {
                mainPanel.removeAll();
                mainPanel.setLayout(new GridLayout(0, 1));
                int count = 1;
                ResultSet dbLaptop = db.selectQuery("select * from laptop");
                int id = 0;
                String cpu = "", vga = "", ram = "", hddssd = "", ukuranLayar = "", jenisLayar = "", jenisPanel = "", resolusiLayar = "", keyboard = "", camera = "";
                int idComponent = 0, idLayar = 0;
                try {
                    while (dbLaptop.next()) {
                        id = dbLaptop.getInt("id_laptop");
                        idComponent = dbLaptop.getInt("id_component");
                        
//                        Component
                        ResultSet dbComponent = db2.selectQuery("select * from component WHERE id_component='"+idComponent+"'");
                        try {
                            if (dbComponent.next()) {
                                cpu = dbComponent.getString("cpu");
                                vga = dbComponent.getString("graphics_card");
                                ram = dbComponent.getString("ram");
                                hddssd = dbComponent.getString("hdd_ssd");
                                idLayar = dbComponent.getInt("id_layar");
                                keyboard = dbComponent.getString("keyboard");
                                camera = dbComponent.getString("camera");
                            }
                        } catch (SQLException ex) {
                            Logger.getLogger(AddComponent.class.getName()).log(Level.SEVERE, null, ex);
                        }
//                        Layar
                        ResultSet dbLayar = db3.selectQuery("select * from layar WHERE id_layar='"+idLayar+"'");
                        try {
                            if (dbLayar.next()) {
                                ukuranLayar = dbLayar.getString("ukuran_layar");
                                jenisLayar = dbLayar.getString("jenis_layar");
                                jenisPanel = dbLayar.getString("jenis_panel");
                                resolusiLayar = dbLayar.getString("resolusi_layar");
                            }
                        } catch (SQLException ex) {
                            Logger.getLogger(AddComponent.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        
                        mainPanel.add(new CardLaptop(db, this, id, count, dbLaptop.getString("merk_laptop") , dbLaptop.getString("model_laptop"), dbLaptop.getString("jenis_laptop"), dbLaptop.getInt("id_component"), dbLaptop.getString("image_laptop"), cpu, vga, ram, hddssd, idLayar, ukuranLayar, jenisLayar, jenisPanel, resolusiLayar, keyboard, camera));
                        count++;
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(AddComponent.class.getName()).log(Level.SEVERE, null, ex);
                }
                mainPanel.revalidate();
                mainPanel.repaint();
            }
        }
    }//GEN-LAST:event_FilterDropDownActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AddDropDown;
    private javax.swing.JButton ClearButton;
    private javax.swing.JComboBox<String> FilterDropDown;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    public static final javax.swing.JLabel nameAccountLabel = new javax.swing.JLabel();
    private javax.swing.JLabel timeLogin;
    private javax.swing.JLabel timeShow;
    // End of variables declaration//GEN-END:variables
}
